# Generated by Django 3.1.8 on 2021-08-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('answer_options', models.TextField(blank=True, verbose_name='Варианты ответа. Каждая строка - новый вариант ответа (точно так же будет вышлядеть инлайн меню). Слово НЕ должно быть больше 32 символов. Для заполнения не обязательно')),
            ],
            options={
                'verbose_name': 'Вопросы для опросника о пользователе',
            },
        ),
    ]
