# Generated by Django 3.1.8 on 2021-08-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminbot', '0002_auto_20210816_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('telegram_id', models.CharField(max_length=20, verbose_name='ID в телеграмме')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('age', models.CharField(max_length=2, verbose_name='Возраст')),
                ('nationality', models.CharField(max_length=255, verbose_name='Национальность')),
                ('education', models.CharField(max_length=255, verbose_name='Образование')),
                ('education_city', models.CharField(max_length=255, verbose_name='Город, где получал образование')),
                ('city', models.CharField(max_length=255, verbose_name='Город текущего проживания')),
                ('profession', models.CharField(max_length=255, verbose_name='Профессия')),
                ('marital_status', models.CharField(max_length=255, verbose_name='Семейное положение')),
                ('has_car', models.CharField(max_length=255, verbose_name='Есть ли автомобиль')),
                ('has_own_housing', models.CharField(max_length=255, verbose_name='Есть ли собственное жилье')),
                ('has_children', models.CharField(max_length=255, verbose_name='Есть ли дети')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
