# Generated by Django 3.1.8 on 2021-08-18 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminbot', '0003_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchquestions',
            name='answer_options',
            field=models.TextField(blank=True, verbose_name='Варианты ответа. Каждая строка - новый вариант ответа (точно так же будет выглядеть инлайн меню). Для заполнения НЕ обязательно'),
        ),
        migrations.AlterField(
            model_name='userquestions',
            name='answer_options',
            field=models.TextField(blank=True, verbose_name='Варианты ответа. Каждая строка - новый вариант ответа (точно так же будет выглядеть инлайн меню). Для заполнения НЕ обязательно'),
        ),
        migrations.CreateModel(
            name='Questionnaires',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('age_range', models.CharField(max_length=7, verbose_name='Диапазон возраста')),
                ('nationality', models.CharField(max_length=255, verbose_name='Национальность')),
                ('education', models.CharField(max_length=255, verbose_name='Образование')),
                ('education_city', models.CharField(max_length=255, verbose_name='Город, где получал образование')),
                ('city', models.CharField(max_length=255, verbose_name='Город текущего проживания')),
                ('profession', models.CharField(max_length=255, verbose_name='Чем должен заниматься')),
                ('marital_status', models.CharField(max_length=255, verbose_name='Семейное положение')),
                ('has_car', models.CharField(max_length=255, verbose_name='Должен ли быть автомобиль')),
                ('has_own_housing', models.CharField(max_length=255, verbose_name='Должно ли быть собственное жилье')),
                ('has_children', models.CharField(max_length=255, verbose_name='Могут ли быть дети')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminbot.users', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Анкета для поиска',
                'verbose_name_plural': 'Анкеты для поиска',
            },
        ),
    ]
