# Generated by Django 3.1.8 on 2021-08-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminbot', '0005_auto_20210818_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(default='Не указан', max_length=256, verbose_name='Юзернейм'),
        ),
        migrations.AlterField(
            model_name='searchquestions',
            name='question_id',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='ID вопроса'),
        ),
        migrations.AlterField(
            model_name='userquestions',
            name='question_id',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='ID вопроса'),
        ),
    ]
