# Generated by Django 3.1.8 on 2021-08-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminbot', '0006_auto_20210819_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='active_to_search',
            field=models.BooleanField(default=True, verbose_name='Активен для поиска'),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=256, null=True, verbose_name='Юзернейм'),
        ),
    ]
