# Generated by Django 3.1.8 on 2021-08-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminbot', '0007_auto_20210819_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='gender',
            field=models.CharField(max_length=1, null=True, verbose_name='Пол'),
        ),
    ]
