# Generated by Django 3.1.8 on 2021-08-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminbot', '0008_users_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(max_length=20, null=True, verbose_name='Пол'),
        ),
    ]
