# Generated by Django 3.1.8 on 2021-08-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminbot', '0009_auto_20210823_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='known_users',
            field=models.JSONField(null=True, verbose_name='Известные пользователи'),
        ),
    ]
